### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 19970222hlx** [florale/multilevelcoda#1]
This is my code:
pkgbuild::find_rtools()
cmdstanr::check_cmdstan_toolchain(fix = TRUE)
install_cmdstan(dir = 'D:/R-4.0.5')
set_cmdstan_path('D:/R-4.0.5/cmdstan-2.32.2')
cmdstan_path()
install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
library(cmdstanr)
library(multilevelcoda)
library(brms)
library(doFuture)
library(bayestestR)
options(digits = 3) # reduce number of digits shown
data("mcompd") 
data("sbp")
data("psub")
cilr <- compilr(data = mcompd, sbp = sbp,
                parts = c("TST", "WAKE", "MVPA", "LPA", "SB"), idvar = "ID", total = 1440)
m <- brmcoda(compilr = cilr,
             formula = Stress ~ bilr1 + bilr2 + bilr3 + bilr4 +
               wilr1 + wilr2 + wilr3 + wilr4 + (1 | ID),
             cores = 8, seed = 123, backend = "cmdstanr")
I have the following error:
> m <- brmcoda(compilr = cilr,
+              formula = Stress ~ bilr1 + bilr2 + bilr3 + bilr4 +
+                wilr1 + wilr2 + wilr3 + wilr4 + (1 | ID),
+              cores = 8, seed = 123, backend = "cmdstanr")
Compiling Stan program...
Error in rethrow_call(c_processx_exec, command, c(command, args), pty,  : 
  Command 'make' not found @win/processx.c:982 (processx_exec)
Type .Last.error.trace to see where the error occurred
And I want to know how to deal with this error, please give me some suggestion, thanks

**Comment by JWiley** [comment]
It looks like the make command is not found. On windows, make sure you have RTools installed and added to your system path 
https://cran.r-project.org/bin/windows/Rtools/

On macOS make sure you have Xcode installed and accessible from terminal.

on Linux like Ubuntu this should do:

```
sudo apt update 
sudo apt install build-essential 
```

**Comment by 19970222hlx** [comment]
Thank you so much, sir!
