### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 19970222hlx** [florale/multilevelcoda#2]
I found another bug:
plotsub(data=subm1$BetweenSub$TST,
+         x='sleep',y='stress')
Error in plotsub(data = subm1$BetweenSub$TST, x = "sleep", y = "stress") : 
  没有"plotsub"这个函数
your valuable suggestion is necessary.

**Comment by JWiley** [comment]
I think `plotsub` is older code — now you can just use `plot` and it uses a method for a substitution object. Check out this vignette:

https://florale.github.io/multilevelcoda/articles/D-substitution-model.html

**Comment by 19970222hlx** [comment]
Thank you so much! This problem has been solved.
