### ISSUE TITLE
classification of response

### ISSUE THREAD

**Issue by 19970222hlx** [florale/multilevelcoda#3]
Excuse me, sir, I have a question.
In the function 'brmcoda', the response in the formula is numeric, such as 'formula = Stress ~ '.
If the response in my data is a categorical outcome, how to include it in the formula?
Looking forward to your reply!

**Comment by florale** [comment]
The formula syntax follows the form of a `brmsfit` object. The left side of `~` is the outcome, meaning that you can replace `Stress` with your categorical variable. For details about the multilevel syntax of `brms`, see `help("brmsformula")`).

**Comment by 19970222hlx** [comment]
Thank you so much!
